# Generated by Django 6.0.1 on 2026-02-05 07:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsFeesExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('expense_name', models.CharField(choices=[('Electricity', 'electricity'), ('Water', 'water'), ('Elevator tax', 'Elevator tax'), ('Cleaner', 'cleaner'), ('Doorman', 'doorman'), ('Gardener', 'gardener'), ('Other', 'other')], default='Other', max_length=55)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RenovationFundExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BillsFeesIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('flat_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.flat')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renovation_fee', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('bills_fee', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_update', models.DateField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.building')),
            ],
            options={
                'verbose_name_plural': 'Monthly Taxes',
            },
        ),
        migrations.CreateModel(
            name='RenovationFundIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flat_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.flat')),
            ],
        ),
    ]
