# Generated by Django 6.0.1 on 2026-02-03 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0003_remove_ownership_building_remove_ownership_citizen_and_more'),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsfeesincomes',
            name='flat_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.flat'),
        ),
        migrations.AlterField(
            model_name='renovationfundincomes',
            name='flat_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.flat'),
        ),
    ]
