# Generated by Django 6.0.1 on 2026-02-03 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_alter_billsfeesincomes_flat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytaxes',
            name='bills_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthlytaxes',
            name='renovation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
