# Generated by Django 6.0.1 on 2026-02-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0007_citizen_role'),
        ('taxes', '0003_alter_monthlytaxes_bills_fee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillsFeesExpenses',
            new_name='BillsFeesExpense',
        ),
        migrations.RenameModel(
            old_name='RenovationFundIncomes',
            new_name='BillsFeesIncome',
        ),
        migrations.RenameModel(
            old_name='MonthlyTaxes',
            new_name='MonthlyTax',
        ),
        migrations.RenameModel(
            old_name='RenovationFundExpenses',
            new_name='RenovationFundExpense',
        ),
        migrations.RenameModel(
            old_name='BillsFeesIncomes',
            new_name='RenovationFundIncome',
        ),
    ]
