# Generated by Django 6.0.1 on 2026-02-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_rename_billsfeesexpenses_billsfeesexpense_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlytax',
            options={'verbose_name_plural': 'Monthly Taxes'},
        ),
        migrations.AlterField(
            model_name='renovationfundincome',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
