# Generated by Django 6.0.2 on 2026-02-16 12:05

import django.core.validators
import documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('type', models.CharField(choices=[('Protocol', 'Протокол'), ('Invoice', 'Фактура'), ('Mail', 'Писмо'), ('Other', 'Друго')], default='Invoice', max_length=25)),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pdf', 'jpg', 'jpeg', 'png']), documents.validators.MaxFileSizeValidator(max_size_mb=5)])),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
