# Generated by Django 6.0.1 on 2026-02-03 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=55)),
                ('street', models.CharField(max_length=125)),
                ('created_at', models.DateField(auto_now=True)),
                ('number_of_flats', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('flat_number', models.PositiveSmallIntegerField()),
                ('role', models.CharField(choices=[('Owner', 'owner'), ('Resident', 'resident'), ('Tenant', 'tenant'), ('Pet', 'pet')], default='Resident', max_length=50)),
                ('building', models.ManyToManyField(to='condominium.building')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.PositiveSmallIntegerField()),
                ('ideal_parts', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('last_update', models.DateField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominium.building')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.citizen')),
            ],
        ),
    ]
