# Generated by Django 6.0.2 on 2026-02-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatresident',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='flatresident',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
