# Generated by Django 6.0.1 on 2026-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='building',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='role',
        ),
        migrations.AddField(
            model_name='ownership',
            name='role',
            field=models.CharField(choices=[('Owner', 'owner'), ('Resident', 'resident'), ('Tenant', 'tenant'), ('Pet', 'pet')], default='Resident', max_length=50),
        ),
    ]
