# Generated by Django 6.0.1 on 2026-02-03 13:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0002_remove_citizen_building_remove_citizen_flat_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='building',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='building',
            name='number_of_flats',
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.PositiveSmallIntegerField()),
                ('ideal_parts', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('last_update', models.DateField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominium.building')),
            ],
        ),
        migrations.CreateModel(
            name='FlatResidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Owner', 'owner'), ('Resident', 'resident'), ('Tenant', 'tenant'), ('Pet', 'pet')], default='Resident', max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.citizen')),
                ('flat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominium.flat')),
            ],
        ),
    ]
