# Generated by Django 6.0.2 on 2026-02-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0002_alter_flatresident_email_alter_flatresident_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatresident',
            name='role',
            field=models.CharField(choices=[('Owner', 'собственик'), ('Resident', 'живущ'), ('Tenant', 'наемател'), ('Pet', 'домашен любимец')], default='Resident', max_length=50),
        ),
    ]
