# Generated by Django 6.0.1 on 2026-02-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0003_remove_ownership_building_remove_ownership_citizen_and_more'),
        ('taxes', '0002_alter_billsfeesincomes_flat_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ownership',
        ),
    ]
