# Generated by Django 6.0.2 on 2026-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0003_alter_flatresident_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatresident',
            name='role',
            field=models.CharField(choices=[('Owner', 'Собственик'), ('Resident', 'Обитател'), ('Tenant', 'Наемател'), ('Pet', 'Домашен любимец')], default='Resident', max_length=50),
        ),
    ]
