# Generated by Django 6.0.1 on 2026-02-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0004_delete_ownership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatresidents',
            old_name='flat_number',
            new_name='flat',
        ),
    ]
