# Generated by Django 6.0.2 on 2026-02-18 18:04

from django.db import migrations

def populate_building_model(apps, schema_editor):
    BuildingModel = apps.get_model('condominium', 'Building')
    BuildingModel.objects.create(
        name = 'Мизия',
        city = 'София',
        street = 'ул. Балкани 1',
    )

def reverse_populate_building_model(apps, schema_editor):
     BuildingModel = apps.get_model('condominium', 'Building')
     BuildingModel.objects.filter(name='Мизия').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0004_alter_flatresident_role'),
    ]

    operations = [
        migrations.RunPython(code=populate_building_model, reverse_code=reverse_populate_building_model)
    ]
