# Generated by Django 6.0.2 on 2026-02-18 18:22

from django.db import migrations

def populate_flat_model(apps, schema_editor):
    FlatModel = apps.get_model('condominium', 'Flat')
    BuildingModel = apps.get_model('condominium', 'Building')

    building = BuildingModel.objects.get(pk=1)

    flats = [
        FlatModel(flat_number=1, floor=1, ideal_parts=10, building=building),
        FlatModel(flat_number=2, floor=1, ideal_parts=10, building=building),
        FlatModel(flat_number=3, floor=2, ideal_parts=10, building=building),
        FlatModel(flat_number=4, floor=2, ideal_parts=10, building=building),
        FlatModel(flat_number=5, floor=3, ideal_parts=10, building=building),
        FlatModel(flat_number=6, floor=3, ideal_parts=10, building=building),
        FlatModel(flat_number=7, floor=4, ideal_parts=10, building=building),
        FlatModel(flat_number=8, floor=4, ideal_parts=10, building=building),
        FlatModel(flat_number=9, floor=5, ideal_parts=8.5, building=building),
        FlatModel(flat_number=10, floor=5, ideal_parts=11.5, building=building),
    ]

    FlatModel.objects.bulk_create(flats)

def reverse_populate_flat_model(apps, schema_editor):
    FlatModel = apps.get_model('condominium', 'Flat')
    BuildingModel = apps.get_model('condominium', 'Building')

    building = BuildingModel.objects.get(pk=1)
    FlatModel.objects.filter(building=building).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0005_populate_bulding_and_flats_model'),
    ]

    operations = [
        migrations.RunPython(code=populate_flat_model, reverse_code=reverse_populate_flat_model)
    ]
