# Generated by Django 6.0.1 on 2026-02-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0005_rename_flat_number_flatresidents_flat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlatResidents',
            new_name='FlatResident',
        ),
    ]
