# Generated by Django 6.0.2 on 2026-02-18 18:38

from django.db import migrations

def populate_flat_residents(apps, schema_editor):
    FlatResident = apps.get_model('condominium', 'FlatResident')
    Flat = apps.get_model('condominium', 'Flat')

    residents = [
        {'first_name': 'Димитър', 'last_name': 'Рачков', 'email': 'dimitar@rachkov.com', 'role': 'Owner', 'flat': 1, 'phone': '+359000111339'},
        {'first_name': 'Иван', 'last_name': 'Иванов', 'email': 'ivan@ivanov.com', 'role': 'Resident', 'flat': 2, 'phone': '+359888444666'},
        {'first_name': 'Александър', 'last_name': 'Александров', 'email': 'alexander@alexandrov.com', 'role': 'Tenant', 'flat': 3, 'phone': '+359888000222'},
        {'first_name': 'Димитър', 'last_name': 'Димитров', 'email': 'dimitar@dimitrov.com', 'role': 'Owner', 'flat': 4, 'phone': '+359888666000'},
        {'first_name': 'Драган', 'last_name': 'Драганов', 'email': 'dragan@draganov.com', 'role': 'Resident', 'flat': 6, 'phone': '+359888777666'},
        {'first_name': 'Мирослав', 'last_name': 'Мирославов', 'email': 'miroslav@miroslavov.com', 'role': 'Tenant', 'flat': 6, 'phone': None},
        {'first_name': 'Светломир', 'last_name': 'Светломиров', 'email': None, 'role': 'Owner', 'flat': 5, 'phone': None},
        {'first_name': 'Десислава', 'last_name': 'Десиславова', 'email': None, 'role': 'Resident', 'flat': 7, 'phone': None},
        {'first_name': 'Кичка', 'last_name': 'Бодурова', 'email': None, 'role': 'Resident', 'flat': 8, 'phone': None},
        {'first_name': 'Мими', 'last_name': 'Иванова', 'email': None, 'role': 'Owner', 'flat': 9, 'phone': '+3598885551111'},
        {'first_name': 'Rocky', 'last_name': 'куче', 'email': None, 'role': 'Pet', 'flat': 10, 'phone': None},
        {'first_name': 'Митко', 'last_name': 'Чуков', 'email': None, 'role': 'Tenant', 'flat': 7, 'phone': None},
        {'first_name': 'Емилия', 'last_name': 'Масларова', 'email': None, 'role': 'Tenant', 'flat': 10, 'phone': None},
        {'first_name': 'Марийка', 'last_name': 'Иванова', 'email': None, 'role': 'Owner', 'flat': 2, 'phone': None},
        {'first_name': 'Развигор', 'last_name': 'Попов', 'email': 'razvigor@popov.com', 'role': 'Resident', 'flat': 9, 'phone': '+359888999777'},
        {'first_name': 'Татяна', 'last_name': 'Лолова', 'email': 'tatiana@lolova.com', 'role': 'Resident', 'flat': 4, 'phone': '+359887555666'},
    ]

    for resident in residents:
        flat = Flat.objects.get(pk=resident['flat'])
        FlatResident.objects.create(
            first_name=resident['first_name'],
            last_name=resident['last_name'],
            email=resident['email'],
            role=resident['role'],
            flat=flat,
            phone=resident['phone']
        )

def reverse_flat_residents(apps, schema_editor):
    FlatResident = apps.get_model('condominium', 'FlatResident')
    FlatResident.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0006_populate_flats_model'),
    ]

    operations = [
        migrations.RunPython(code=populate_flat_residents,  reverse_code=reverse_flat_residents),
    ]
