# Generated by Django 6.0.1 on 2026-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0006_rename_flatresidents_flatresident'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='role',
            field=models.CharField(choices=[('Condominium manager', 'condominium manager'), ('Condominium cashier', 'condominium cashier'), ('Resident', 'Resident')], default='Resident', max_length=55),
        ),
    ]
