# Generated by Django 6.0.1 on 2026-02-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0007_citizen_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('building', 'flat_number')},
        ),
    ]
