# Generated by Django 6.0.2 on 2026-02-11 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominium', '0003_alter_flatresident_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Accepted', max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.flatresident')),
            ],
        ),
    ]
