# Generated by Django 6.0.2 on 2026-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Приета'), ('In Progress', 'Изпълнява се'), ('Done', 'Изпълнена')], default='Accepted', max_length=25),
        ),
    ]
